import { ATTRIBUTES, cloneAttributes } from './types';
import type { Attributes, Character, Recommendation, SkillRecommendation } from './types';
import { SKILLS, ATTRIBUTE_PRIORITIES } from './data';
const weights=(c:Character)=>(ATTRIBUTE_PRIORITIES[c.id as keyof typeof ATTRIBUTE_PRIORITIES]??ATTRIBUTE_PRIORITIES.default).weights;
const priority=(c:Character):(keyof Attributes)[]=>{const score:Record<string,number>={D:1,C:2,B:3,A:4,S:5};const entered=c.weaponScaling??Object.fromEntries(Object.entries(c.scaling?.attributes??{}).map(([a,v])=>[a,v.toUpperCase()]));const scaling=Object.entries(entered).sort(([,a],[,b])=>(score[b]??0)-(score[a]??0)).map(([a])=>a as keyof Attributes);return [...new Set([...scaling,...ATTRIBUTES.slice().sort((a,b)=>weights(c)[b]-weights(c)[a])])];};
export function recommend(c:Character):Recommendation{const spend:Partial<Attributes>={};let left=Math.max(0,c.points);while(left){let moved=false;for(const a of priority(c)){if(!left)break;if(c.invested[a]+(spend[a]??0)<99){spend[a]=(spend[a]??0)+1;left--;moved=true;}}if(!moved)break;}const scaling=Object.keys(c.weaponScaling??c.scaling?.attributes??{}).length>0;return{characterId:c.id,base:cloneAttributes(c.invested),basePoints:c.points,spend,points:c.points-left,explanation:c.points?(scaling?'Prioritises your entered weapon-scaling attributes, then survivability and reliable damage. Scaling is directional advice, not a full equipment optimiser.':'Prioritises survivability first, then reliable damage, while respecting each attribute cap. Equipped-weapon scaling is not considered until you enter it.'):'There are no available attribute points to allocate.',revision:c.level};}
export function applyRecommendation(c:Character,r:Recommendation):Character{if(r.revision!==c.level||r.characterId!==c.id||ATTRIBUTES.some(a=>r.base[a]!==c.invested[a])||r.points>c.points||(r.basePoints!==undefined&&r.basePoints!==c.points))return c;if(!Number.isInteger(r.points)||r.points<0||Object.values(r.spend).some(v=>!Number.isInteger(v)||v!<0)||r.points!==Object.values(r.spend).reduce((a,v)=>a+(v??0),0))return c;const invested=cloneAttributes(c.invested);for(const a of ATTRIBUTES){const n=r.spend[a]??0;if(invested[a]+n>99)return c;invested[a]+=n;}return{...c,invested,points:c.points-r.points,pending:undefined};}
export function updateProgress(c:Character,i:{level:number;invested:Attributes;points:number}):Character{if(!Number.isInteger(i.level)||i.level<1||i.level>99||!Number.isInteger(i.points)||i.points<0||ATTRIBUTES.some(a=>!Number.isInteger(i.invested[a])||i.invested[a]<0||i.invested[a]>99))throw new Error('Enter whole numbers within the supported level and attribute ranges.');return{...c,level:i.level,invested:cloneAttributes(i.invested),points:i.points,pending:undefined,pendingSkill:undefined};}
export function recommendSkill(c:Character):SkillRecommendation|null{if(!c.skillSetupComplete||c.skillPoints===undefined||!c.unlockedSkills)return null;if(c.id==='monoco')return{characterId:c.id,save:true,points:0,explanation:'This character learns skills through discovered encounters. Record a skill after you confirm learning it; no skill-point purchase is suggested.',revision:c.level,baseSkillPoints:c.skillPoints,baseUnlockedSkills:[...c.unlockedSkills]};const owned=new Set(c.unlockedSkills),disc=new Set(c.discoveredSkillIds??[]),s=(SKILLS[c.id]??[]).find(s=>!s.starting&&s.acquisition!=='learned'&&!s.unsupportedPurchase&&(!s.storyGated||disc.has(s.id))&&!owned.has(s.id)&&(s.requires??[]).every(x=>owned.has(x))&&(s.requiresAny??[]).every(g=>g.some(x=>owned.has(x)))&&s.cost<=c.skillPoints!);return{characterId:c.id,skillId:s?.id,save:!s,points:s?.cost??0,explanation:s?`Unlock ${s.name} for ${s.cost} skill point${s.cost===1?'':'s'}.`:'Save your skill points until a visible skill is affordable and its prerequisites are met.',revision:c.level,baseSkillPoints:c.skillPoints,baseUnlockedSkills:[...c.unlockedSkills]};}
export function applySkillRecommendation(c:Character,r:SkillRecommendation):Character{if(r.characterId!==c.id||r.revision!==c.level||!c.skillSetupComplete||c.skillPoints===undefined||!c.unlockedSkills||r.baseSkillPoints!==c.skillPoints||JSON.stringify(r.baseUnlockedSkills)!==JSON.stringify(c.unlockedSkills))return c;if(r.save||!r.skillId)return{...c,pendingSkill:undefined};const s=(SKILLS[c.id]??[]).find(x=>x.id===r.skillId);if(!s||s.starting||s.acquisition==='learned'||s.unsupportedPurchase||r.points!==s.cost||s.storyGated&&!(c.discoveredSkillIds??[]).includes(s.id)||c.unlockedSkills.includes(s.id)||!(s.requires??[]).every(x=>c.unlockedSkills!.includes(x))||!(s.requiresAny??[]).every(g=>g.some(x=>c.unlockedSkills!.includes(x)))||s.cost>c.skillPoints)return c;return{...c,unlockedSkills:[...c.unlockedSkills,s.id],skillPoints:c.skillPoints-s.cost,pendingSkill:undefined};}
export function suggestLoadout(c:Character):string[]{if(!c.skillSetupComplete)return[];const owned=new Set(c.unlockedSkills??[]);const catalog=(SKILLS[c.id]??[]).filter(s=>owned.has(s.id)&&(!s.storyGated||(c.discoveredSkillIds??[]).includes(s.id))).map(s=>s.id);const known=new Set(catalog);return [...catalog,...[...owned].filter(id=>!known.has(id))].slice(0,6);}
export function recordLoadout(c:Character,l:string[]):Character{const owned=new Set(c.unlockedSkills??[]);return{...c,loadout:[...new Set(l)].filter(id=>owned.has(id)).slice(0,6)};}
