<script setup lang="ts">
import { computed, ref } from 'vue';
import { INITIAL_CHARACTERS, LATER_CHARACTERS, attributeLabels } from '../domain/data';
import { ATTRIBUTES, emptyAttributes } from '../domain/types';
import type { Character, Playthrough, SaveData } from '../domain/types';
import { applyRecommendation, recommend, updateProgress } from '../domain/rules';
import { id, load, save } from '../domain/storage';
import CharacterCard from './CharacterCard.vue'; import FocusDialog from './FocusDialog.vue'; import SetupPanel from './SetupPanel.vue';
const loaded = typeof localStorage !== 'undefined' ? load() : { kind: 'missing' as const }; const state = ref<SaveData | null>(loaded.kind === 'loaded' ? loaded.data : null); const unreadableSave = loaded.kind === 'invalid';
const setupName = ref('My Expedition'); const selected = ref<string[]>(['gustave','lune']); const saveError = ref(loaded.kind === 'invalid' ? loaded.error : ''); const notice = ref(''); const revealStage = ref<'warning'|'identity'|'terminal'|null>(null); const setupCharacter = ref<Character|null>(null); const formError = ref(''); const addingCandidate = ref(false); const revealedCandidate = ref<typeof LATER_CHARACTERS[number]|null>(null); const draft = ref({level:1,points:0,invested:emptyAttributes()});
const active = computed(() => state.value?.playthroughs.find(p => p.id === state.value?.activeId) ?? null); const snapshot = () => state.value ? JSON.parse(JSON.stringify(state.value)) as SaveData : null;
function persist(before: SaveData|null) { if (!state.value) return true; const result = save(state.value); if (!result.ok) { state.value = before; saveError.value = result.error ?? 'Your browser could not save this change.'; return false; } saveError.value = ''; notice.value = 'Saved'; return true; }
function start(actual: Record<string, {level:number;points:number;invested:typeof draft.value.invested}|null> = {}) { if (unreadableSave || !selected.value.length) return; const before = snapshot(); try { const characters = selected.value.map(key => { const d = INITIAL_CHARACTERS[key as keyof typeof INITIAL_CHARACTERS]; const input = actual[key]; if (input) return updateProgress({id:key,name:d.name,level:1,invested:{...d.defaults},points:3,tracked:true,revealed:true}, input); return {id:key,name:d.name,level:1,invested:{...d.defaults},points:3,tracked:true,revealed:true}; }); const p:Playthrough={id:id('playthrough'),name:setupName.value.trim()||'My Expedition',characters,nextRevealIndex:0,revision:0}; state.value={version:1,playthroughs:[p],activeId:p.id}; persist(before); } catch (e) { saveError.value = e instanceof Error ? e.message : 'Enter valid in-game progress.'; } }
function beginSetup(c: Character) { formError.value=''; setupCharacter.value=c; draft.value={level:c.level,points:c.points,invested:{...c.invested}}; }
function submitProgress() { if (!active.value || !setupCharacter.value) return; try { const before=snapshot(); const c=updateProgress({...setupCharacter.value},draft.value); if(addingCandidate.value&&revealedCandidate.value){active.value.characters.push(c);active.value.nextRevealIndex++;addingCandidate.value=false;revealedCandidate.value=null;}else{const i=active.value.characters.findIndex(x=>x.id===setupCharacter.value?.id);active.value.characters[i]=c;}active.value.revision++;if(persist(before))setupCharacter.value=null;formError.value='';}catch(e){formError.value=e instanceof Error?e.message:'Enter valid in-game progress.';} }
function advise(c: Character){const before=snapshot();c.pending=recommend(c);persist(before);} function confirm(c: Character){if(!c.pending||!active.value)return;const before=snapshot();const changed=applyRecommendation(c,c.pending);if(changed===c){notice.value='That advice is stale; update progress before applying it.';return;}Object.assign(c,changed);active.value.revision++;if(persist(before))notice.value='Applied recommendation recorded once.';}
function openReveal(){revealStage.value='warning'} function consentReveal(){if(!active.value)return;const n=active.value.nextRevealIndex;revealStage.value=n<LATER_CHARACTERS.length?'identity':'terminal';if(n<LATER_CHARACTERS.length)revealedCandidate.value=LATER_CHARACTERS[n];} function addLater(){if(!revealedCandidate.value)return;const d=revealedCandidate.value;addingCandidate.value=true;revealStage.value=null;beginSetup({id:d.id,name:d.name,level:1,invested:{...d.defaults},points:0,tracked:true,revealed:true});} function cancelReveal(){revealStage.value=null;if(addingCandidate.value){addingCandidate.value=false;setupCharacter.value=null;}}
</script>
<template><main class="shell"><p v-if="saveError" class="error" role="alert">{{saveError}}</p><header><p class="eyebrow">EXPEDITION 33 · FIELD GUIDE</p><h1>Keep your build on course.</h1><p class="lede">A quiet companion for recording real progress and choosing the next safe step.</p></header><SetupPanel v-if="!state" v-model:name="setupName" :selected="selected" :disabled="unreadableSave||!!saveError" @update:selected="selected=$event" @start="start"/><template v-else-if="active"><nav class="bar"><strong>{{active.name}}</strong><span aria-live="polite">{{notice}}</span></nav><section class="party"><CharacterCard v-for="c in active.characters.filter(x=>x.tracked)" :key="c.id" :character="c" @update="beginSetup" @advise="advise" @confirm="confirm"/></section><button class="add" @click="openReveal">＋ Add a character</button><p class="research">Guidance is based on recorded in-game progress. Initial defaults and priorities are kept with the guide's research notes; recommendations are editorial advice.</p></template>
<FocusDialog v-if="setupCharacter" :title="`Update ${setupCharacter.name}`" @close="setupCharacter=null"><p>Enter what is true in-game. This replaces the recorded inputs and clears old advice.</p><p v-if="formError" class="error" role="alert">{{formError}}</p><form @submit.prevent="submitProgress"><label>Current level<input type="number" min="1" max="99" v-model.number="draft.level"/></label><label>Available attribute points<input type="number" min="0" v-model.number="draft.points"/></label><div class="edit-grid"><label v-for="a in ATTRIBUTES" :key="a">{{attributeLabels[a]}}<input type="number" min="0" max="99" v-model.number="draft.invested[a]"/></label></div><div class="actions"><button type="button" @click="setupCharacter=null">Cancel</button><button class="primary">Save progress</button></div></form></FocusDialog>
<FocusDialog v-if="revealStage" title="Continue your expedition?" @close="cancelReveal"><p v-if="revealStage==='warning'">Only continue if someone new has joined your party. The next identity stays hidden until you choose to reveal it.</p><p v-else-if="revealStage==='identity'">The next character is <strong>{{revealedCandidate?.name}}</strong>.</p><p v-else>No additional character is available right now.</p><div class="actions"><button @click="cancelReveal">Cancel</button><button v-if="revealStage==='warning'" class="primary" @click="consentReveal">Reveal character</button><button v-else-if="revealStage==='identity'" class="primary" @click="addLater">Add to playthrough</button></div></FocusDialog></main></template>
<style>.shell{max-width:960px;margin:auto;padding:48px 22px 80px;color:#f6f1e8;background:#171717;min-height:100vh}.card{background:#242322;border:1px solid #514942;border-radius:18px;padding:24px}.party{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.modal-backdrop{position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:18px;z-index:2}.modal{background:#242322;border:1px solid #776452;border-radius:18px;padding:26px;max-width:520px;width:100%}.error{color:#ffb4a8}button{padding:10px 14px}.add{display:block;width:100%;margin:22px 0;padding:16px}label{display:grid;gap:7px;margin:16px 0}input{padding:10px;width:100%}.edit-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}</style>
