<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import { INITIAL_CHARACTERS, LATER_CHARACTERS, attributeLabels } from '../domain/data';
import { ATTRIBUTES, emptyAttributes } from '../domain/types';
import type { Attributes, Character, Playthrough, SaveData } from '../domain/types';
import { applyRecommendation, recommend, updateProgress } from '../domain/rules';
import { id, load, save } from '../domain/storage';
const loaded = typeof localStorage !== 'undefined' ? load() : {kind:'missing' as const};
const state = ref<SaveData | null>(loaded.kind === 'loaded' ? loaded.data : null);
const unreadableSave = loaded.kind === 'invalid';
const setupName = ref('My Expedition'); const selected = ref<('gustave'|'lune')[]>(['gustave','lune']); const saveError = ref(''); const notice = ref('');
const revealStage = ref<'warning'|'identity'|'terminal'|null>(null); const setupCharacter = ref<Character | null>(null); const draft = ref({level:1, points:0, invested:emptyAttributes()});
const revealedCandidate = ref<typeof LATER_CHARACTERS[number] | null>(null); const addingCandidate = ref(false);
if (loaded.kind === 'invalid') saveError.value = loaded.error;
const closeOnEscape = (event: KeyboardEvent) => { if (event.key === 'Escape') { revealStage.value = null; setupCharacter.value = null; } };
onMounted(() => window.addEventListener('keydown', closeOnEscape)); onUnmounted(() => window.removeEventListener('keydown', closeOnEscape));
const active = computed(() => state.value?.playthroughs.find(p => p.id === state.value?.activeId) ?? null);
const persist = () => { if (!state.value) return; const result = save(state.value); saveError.value = result.error ?? ''; if (result.ok) notice.value = 'Saved'; };
function start() { if (unreadableSave) return; const chars = selected.value.map(id0 => { const d=INITIAL_CHARACTERS[id0]; return {id:id0,name:d.name,level:1,invested:{...d.defaults},points:3,tracked:true,revealed:true}; }); const p:Playthrough={id:id('playthrough'),name:setupName.value.trim()||'My Expedition',characters:chars,nextRevealIndex:0,revision:0}; state.value={version:1,playthroughs:[p],activeId:p.id}; persist(); }
function beginSetup(character: Character) { setupCharacter.value=character; draft.value={level:character.level,points:character.points,invested:{...character.invested}}; }
function submitProgress() { if (!active.value || !setupCharacter.value) return; const p=active.value; if (addingCandidate.value && revealedCandidate.value) { const c=updateProgress({...setupCharacter.value},draft.value); p.characters.push(c); p.nextRevealIndex++; revealedCandidate.value=null; addingCandidate.value=false; } else { const i=p.characters.findIndex(c=>c.id===setupCharacter.value!.id); p.characters[i]=updateProgress(p.characters[i],draft.value); } p.revision++; setupCharacter.value=null; persist(); }
function advise(c: Character) { c.pending=recommend(c); persist(); }
function confirm(c: Character) { if (!c.pending) return; const changed=applyRecommendation(c,c.pending); if (changed !== c) { Object.assign(c,changed); active.value!.revision++; persist(); notice.value='Applied recommendation recorded once.'; } else notice.value='That advice is stale; update progress before applying it.'; }
function openReveal() { revealStage.value='warning'; }
function consentReveal() { if (!active.value) return; const n=active.value.nextRevealIndex; revealStage.value=n < LATER_CHARACTERS.length ? 'identity' : 'terminal'; if (n < LATER_CHARACTERS.length) revealedCandidate.value=LATER_CHARACTERS[n]; }
function addLater() { if (!revealedCandidate.value) return; const c:Character={id:revealedCandidate.value.id,name:revealedCandidate.value.name,level:1,invested:emptyAttributes(),points:0,tracked:true,revealed:true}; addingCandidate.value=true; revealStage.value=null; beginSetup(c); }
function cancelReveal() { revealStage.value=null; if (addingCandidate.value) { addingCandidate.value=false; setupCharacter.value=null; } }
</script>
<template>
  <main class="shell">
    <p v-if="saveError" class="error" role="alert">{{saveError}}</p>
    <header><p class="eyebrow">EXPEDITION 33 · FIELD GUIDE</p><h1>Keep your build on course.</h1><p class="lede">A quiet companion for recording real progress and choosing the next safe step.</p></header>
    <section v-if="!state" class="card setup"><h2>Start a playthrough</h2><p>Name this run and choose only the characters you want to track now.</p><label>Playthrough name<input v-model="setupName" aria-label="Playthrough name" :disabled="unreadableSave" /></label><fieldset><legend>Initial characters</legend><label v-for="(d,key) in INITIAL_CHARACTERS" :key="key" class="check"><input type="checkbox" :value="key" v-model="selected" :disabled="unreadableSave" /> {{d.name}}</label></fieldset><button class="primary" @click="start" :disabled="unreadableSave || !!saveError">Create playthrough</button></section>
    <template v-else-if="active">
      <nav class="bar"><strong>{{active.name}}</strong><span class="save-state" aria-live="polite">{{notice}}</span></nav>
      <section class="party"><article v-for="c in active.characters.filter(c=>c.tracked)" :key="c.id" class="card character"><div class="card-head"><div><p class="eyebrow">TRACKED CHARACTER</p><h2>{{c.name}}</h2></div><span class="level">LV {{c.level}}</span></div><div class="stats"><div v-for="a in ATTRIBUTES" :key="a"><span>{{attributeLabels[a]}}</span><b>{{c.invested[a]}}</b></div></div><p v-if="c.pending" class="advice"><strong>Pending recommendation</strong><br /><span v-for="(amount,a) in c.pending.spend" :key="a">+{{amount}} {{attributeLabels[a] }} </span><br /><small>{{c.pending.explanation}}</small></p><div class="actions"><button @click="beginSetup(c)">Update progress</button><button @click="advise(c)">Get advice <span class="sr-only">for {{c.name}}</span></button><button v-if="c.pending" class="primary" @click="confirm(c)">I've applied these</button></div><p class="points">{{c.points}} attribute points available</p></article></section>
      <button class="add" @click="openReveal">＋ Add a character</button>
      <p class="research">Guidance is based on recorded in-game progress. Initial defaults and priorities are kept with the guide's research notes; recommendations are editorial advice, not a claim of optimality.</p>
    </template>
    <div v-if="setupCharacter" class="modal-backdrop"><form class="modal" @submit.prevent="submitProgress"><h2>Update {{setupCharacter.name}}</h2><p>Enter what is true in-game. This replaces the recorded inputs and clears old advice.</p><label>Current level<input type="number" min="1" v-model.number="draft.level" /></label><label>Available attribute points<input type="number" min="0" v-model.number="draft.points" /></label><div class="edit-grid"><label v-for="a in ATTRIBUTES" :key="a">{{attributeLabels[a]}}<input type="number" min="0" max="99" v-model.number="draft.invested[a]" /></label></div><div class="actions"><button type="button" @click="setupCharacter=null">Cancel</button><button class="primary">Save progress</button></div></form></div>
    <div v-if="revealStage" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="reveal-title"><h2 id="reveal-title">Continue your expedition?</h2><p v-if="revealStage==='warning'">Only continue if someone new has joined your party. The next identity stays hidden until you choose to reveal it.</p><template v-else-if="revealStage==='identity'"><p>The next character is <strong>{{revealedCandidate?.name}}</strong>.</p><p>Adding them is separate; enter the progress you actually have in-game.</p></template><p v-else>No additional character is available right now.</p><div class="actions"><button @click="cancelReveal">Cancel</button><button v-if="revealStage==='warning'" class="primary" @click="consentReveal">Reveal character</button><button v-else-if="revealStage==='identity'" class="primary" @click="addLater">Add to playthrough</button></div></section></div>
  </main>
</template>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#f6f1e8;background:#171717}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 20% 0,#3b2b28,transparent 45%),#171717;min-height:100vh}.shell{max-width:960px;margin:auto;padding:48px 22px 80px}header{max-width:650px;margin-bottom:32px}.eyebrow{font-size:11px;letter-spacing:.18em;color:#d5a477;margin:0 0 10px}.lede{font-size:18px;color:#c4bdb4;line-height:1.5}h1{font-size:clamp(34px,6vw,64px);line-height:.98;margin:0;letter-spacing:-.05em}h2{margin:0 0 12px}.card{background:#242322;border:1px solid #514942;border-radius:18px;padding:24px;box-shadow:0 15px 50px #0004}.setup{max-width:560px}label{display:grid;gap:7px;color:#cfc6bb;margin:16px 0}input{background:#171717;color:#fff;border:1px solid #655d55;border-radius:8px;padding:10px;font:inherit;width:100%}fieldset{border:1px solid #514942;border-radius:12px;margin:24px 0;padding:10px 16px}.check{display:flex;align-items:center;gap:10px}.check input{width:auto}.primary,button{border:1px solid #88705d;background:transparent;color:#fff;border-radius:9px;padding:10px 14px;font:inherit;cursor:pointer}.primary{background:#c77f4e;border-color:#e0a071;color:#1b1410}.bar{display:flex;align-items:center;gap:18px;margin-bottom:22px}.save-state{color:#b8d7b0;flex:1}.link{border:0;color:#d5a477}.party{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.card-head{display:flex;justify-content:space-between}.level{color:#d5a477;font-weight:700}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin:22px 0}.stats div{background:#171717;border-radius:7px;padding:8px 4px;text-align:center}.stats span{display:block;font-size:10px;color:#aaa}.advice{background:#32271f;padding:13px;border-radius:9px;line-height:1.5}.advice small{color:#d0c2b5}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.points,.research{color:#aaa;font-size:13px}.add{display:block;width:100%;margin:22px 0;padding:16px;border:1px dashed #776452;background:transparent;color:#ddac7d;border-radius:13px}.modal-backdrop{position:fixed;inset:0;background:#000b;display:grid;place-items:center;padding:18px;z-index:2}.modal{background:#242322;border:1px solid #776452;border-radius:18px;padding:26px;max-width:520px;width:100%;max-height:90vh;overflow:auto}.edit-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.edit-grid label{margin:4px 0}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@media(max-width:600px){.shell{padding:32px 15px}.stats{grid-template-columns:repeat(3,1fr)}.bar{align-items:flex-start;flex-wrap:wrap}.save-state{order:3;flex-basis:100%}}
</style>
